spring.datasource:
  #url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql:3306/globalinsurancedb?useSSL=true&nullCatalogMeansCurrent=true 
  username: root
  password: password
#spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: update
 
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
#  default-serialization-format: application/json
server.port: 7080
#spring.cloud.stream.kafka.binder.brokers: localhost:9092
#spring.cloud.stream.kafka.binder.autoCreateTopics: false
#spring.cloud.stream.bindings.stock-out.destination=vstock2022
#spring.cloud.stream.bindings.stock-out.content-type=application/json
#spring.cloud.stream.bindings.payment-in.destination=vpayment2022
#spring.cloud.stream.bindings.payment-in.content-type=application/json


